---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/master

- hosts: worker
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/worker