---
- name: Install etcd
  apt:
    name: etcd
    state: present
    update_cache: true

- name: Change etcd data directory permissions
  file:
    path: "{{ item }}"
    owner: "etcd"
    group: "etcd"
    recurse: yes
  with_items:
    - /etc/etcd
    - "{{ etcd.data_dir }}"
    - "{{ etcd.initial_ca_dir }}"

- name: Generate /etc/default/etcd file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etcd.j2", dest: "/etc/default/etcd", mode: 0644 }
    - { src: "etcd_env.sh", dest: "/root/etcd_env.sh", mode: 755 }
  notify: Restart etcd.service

- name: Enable etcd and restart etcd
  systemd:
    name: etcd.service
    enabled: yes
